name: creativetodo
description: A creative to-do list app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_slidable: ^3.0.1

flutter:
  uses-material-design: true
